; Full-color renderer ownership vocabulary.
; Numeric encodings are stable inside the ROM/debug carrier; external tools bind
; the symbolic names rather than treating the values as a public data format.

const_def
const RENDERER_YELLOW
const RENDERER_FULL_COLOR_OVERWORLD

const_def
const YELLOW_ACTIVE
const HANDOFF_TO_OVERWORLD
const OVERWORLD_RECONSTRUCTING
const OVERWORLD_ACTIVE
const OVERWORLD_OVERLAY
const HANDOFF_TO_YELLOW

const_def
const ACCEPTED
const COALESCED
const DEFERRED
const REJECTED_WRONG_OWNER
const REJECTED_STALE_GENERATION
const REJECTED_CAPACITY

const_def
const PENDING
const PREPARED
const COMMITTING
const COMPLETE
const CANCELLED

const_def
const HANDOFF
const RESET
const SUPERSEDED
const STALE_GENERATION

DEF RENDERER_JOB_NONE EQU $ff
DEF CANCELLATION_NONE EQU $ff

; Temporary names consumed by the Phase 1 placement measurement. The generated
; measurement record selects bank 2 at D000-D00C; later placement tooling may
; replace only this constant without changing the ownership ABI.
DEF PHASE1_SELECTED_WRAM_BANK EQU 2
DEF PHASE1_OWNERSHIP_STATE_BYTES EQU 13
DEF PHASE1_OWNERSHIP_ROM_BANK EQU $3b

DEF FULL_COLOR_ASSERT_NONE EQU 0
DEF FULL_COLOR_ASSERT_GENERATION_EXHAUSTED EQU 1
DEF FULL_COLOR_ASSERT_OWNER_OR_GENERATION EQU 2
DEF FULL_COLOR_ASSERT_ILLEGAL_JOB_TRANSITION EQU 3
DEF FULL_COLOR_ASSERT_COMMIT_IN_PROGRESS EQU 4

; Keep symbolic encodings in generated .sym files for runtime/model adapters.
EXPORT RENDERER_YELLOW, RENDERER_FULL_COLOR_OVERWORLD
EXPORT YELLOW_ACTIVE, HANDOFF_TO_OVERWORLD, OVERWORLD_RECONSTRUCTING
EXPORT OVERWORLD_ACTIVE, OVERWORLD_OVERLAY, HANDOFF_TO_YELLOW
EXPORT ACCEPTED, COALESCED, DEFERRED, REJECTED_WRONG_OWNER
EXPORT REJECTED_STALE_GENERATION, REJECTED_CAPACITY
EXPORT PENDING, PREPARED, COMMITTING, COMPLETE, CANCELLED
EXPORT HANDOFF, RESET, SUPERSEDED, STALE_GENERATION
EXPORT RENDERER_JOB_NONE, CANCELLATION_NONE
