; Full-color renderer ownership vocabulary.
; Numeric encodings are stable inside the ROM/debug carrier; external tools bind
; the symbolic names rather than treating the values as a public data format.

const_def
const RENDERER_YELLOW
const RENDERER_FULL_COLOR_OVERWORLD

const_def
const YELLOW_ACTIVE
const HANDOFF_TO_OVERWORLD
const OVERWORLD_RECONSTRUCTING
const OVERWORLD_ACTIVE
const OVERWORLD_OVERLAY
const HANDOFF_TO_YELLOW
const YELLOW_RECONSTRUCTING

const_def
const RENDERER_CONTEXT_ORDINARY_MAP
const RENDERER_CONTEXT_OVERLAY
const RENDERER_CONTEXT_DIALOGUE
const RENDERER_CONTEXT_MENU
const RENDERER_CONTEXT_BATTLE
const RENDERER_CONTEXT_STANDALONE
const RENDERER_CONTEXT_BOOT_RESET
DEF NUM_RENDERER_CONTEXTS EQU const_value

; Preference and policy are linked in Phase 1, but production dispatch remains
; closed until the later activation checkpoint has proved every handoff.
DEF FULL_COLOR_PRODUCTION_ACTIVATED EQU 0

IF DEF(FULL_COLOR_PRODUCTION_LINKAGE)
INCLUDE "constants/full_color_timing_constants.asm"

const_def
const VBLANK_ROUTE_CLOSED
const VBLANK_ROUTE_YELLOW
const VBLANK_ROUTE_COLOR

const_def
const TRANSITION_NONE
const TRANSITION_REQUIRED

const_def
const TRANSITION_ROUTE_NONE
const TRANSITION_ROUTE_YELLOW
const TRANSITION_ROUTE_FULL_COLOR
const TRANSITION_ROUTE_RESET_YELLOW

DEF FULL_COLOR_RECONSTRUCTION_ITEM_MAP_TILESET_OVERRIDES EQU 1 << 0
DEF FULL_COLOR_RECONSTRUCTION_ITEM_VIEWPORT_DESTINATION EQU 1 << 1
DEF FULL_COLOR_RECONSTRUCTION_ITEM_TILES_REPLACEMENTS EQU 1 << 2
DEF FULL_COLOR_RECONSTRUCTION_ITEM_TILEMAPS_ATTRIBUTES EQU 1 << 3
DEF FULL_COLOR_RECONSTRUCTION_ITEM_PALETTES EQU 1 << 4
DEF FULL_COLOR_RECONSTRUCTION_ITEM_OAM EQU 1 << 5
DEF FULL_COLOR_RECONSTRUCTION_ITEM_SCHEDULER EQU 1 << 6
DEF FULL_COLOR_RECONSTRUCTION_ITEM_MACHINE_STATE EQU 1 << 7
DEF FULL_COLOR_RECONSTRUCTION_LEDGER_COMPLETE EQU $00ff
ENDC

const_def
const ACCEPTED
const COALESCED
const DEFERRED
const REJECTED_WRONG_OWNER
const REJECTED_STALE_GENERATION
const REJECTED_CAPACITY

const_def
const PENDING
const PREPARED
const COMMITTING
const COMPLETE
const CANCELLED

const_def
const HANDOFF
const RESET
const SUPERSEDED
const STALE_GENERATION

DEF RENDERER_JOB_NONE EQU $ff
DEF CANCELLATION_NONE EQU $ff

; Temporary names consumed by the Phase 1 placement measurement. The generated
; measurement record selects bank 2 at D000-D00C; later placement tooling may
; replace only this constant without changing the ownership ABI.
DEF PHASE1_SELECTED_WRAM_BANK EQU 2
DEF PHASE1_OWNERSHIP_STATE_BYTES EQU 13
DEF PHASE1_OWNERSHIP_ROM_BANK EQU $3b

; Measured Phase 2 representation. These are link-time architecture constants,
; not an external ABI.
DEF FULL_COLOR_PHASE2_WRAM_BANK EQU 2
DEF FULL_COLOR_PHASE2_WRAM_START EQU $d00d
DEF FULL_COLOR_PHASE2_WRAM_END EQU $d3d5
DEF FULL_COLOR_PHASE2_ROM_BANK EQU $3b
DEF FULL_COLOR_PHASE2_ROM_START EQU $452b
DEF FULL_COLOR_PHASE2_ROM_END EQU $552b
DEF FULL_COLOR_PHASE3_WRAM_START EQU FULL_COLOR_PHASE2_WRAM_END
; Lifecycle state includes two immutable producer planes for the largest
; supported 20x18 visible unit. Keep the guarded allocation below $d800.
DEF FULL_COLOR_PHASE3_WRAM_END EQU $d7fa
DEF FULL_COLOR_PHASE3_ROM_START EQU FULL_COLOR_PHASE2_ROM_END
DEF FULL_COLOR_PHASE2_SRAM_BANK EQU 3
DEF FULL_COLOR_PHASE2_SRAM_START EQU $beaf
DEF FULL_COLOR_PHASE2_SRAM_END EQU $bfcf
DEF FULL_COLOR_REQUEST_CAPACITY EQU 8
DEF FULL_COLOR_REQUEST_DESCRIPTOR_BYTES EQU 20
DEF FULL_COLOR_REQUEST_SCRATCH_BYTES EQU 808
DEF FULL_COLOR_PRODUCER_PLANE_BYTES EQU SCREEN_AREA
DEF FULL_COLOR_RECONSTRUCTION_WIDTH EQU SCREEN_WIDTH
DEF FULL_COLOR_RECONSTRUCTION_HEIGHT EQU SCREEN_HEIGHT

const_def
const FULL_COLOR_REQUEST_ANIMATION_REPLACEMENT
const FULL_COLOR_REQUEST_BG_PALETTE_PAYLOAD
const FULL_COLOR_REQUEST_MAP_COLUMN_PAIRED
const FULL_COLOR_REQUEST_MAP_CONNECTION_PAIRED
const FULL_COLOR_REQUEST_MAP_OVERLAY_PAIRED
const FULL_COLOR_REQUEST_MAP_RECTANGLE_PAIRED
const FULL_COLOR_REQUEST_MAP_ROW_PAIRED
const FULL_COLOR_REQUEST_OAM_BATCH_AND_DMA
const FULL_COLOR_REQUEST_OBJ_PALETTE_PAYLOAD
DEF NUM_FULL_COLOR_REQUEST_CLASSES EQU const_value

DEF FULL_COLOR_DESCRIPTOR_STATE_CLASS EQU 0
DEF FULL_COLOR_DESCRIPTOR_OWNER EQU 1
DEF FULL_COLOR_DESCRIPTOR_GENERATION EQU 2
DEF FULL_COLOR_DESCRIPTOR_DESTINATION EQU 6
DEF FULL_COLOR_DESCRIPTOR_SOURCE EQU 8
DEF FULL_COLOR_DESCRIPTOR_DESIRED_STATE EQU 10
DEF FULL_COLOR_DESCRIPTOR_RESOURCE_MASK EQU 12
DEF FULL_COLOR_DESCRIPTOR_EXTENT EQU 14
DEF FULL_COLOR_DESCRIPTOR_RESERVATION EQU 16
DEF FULL_COLOR_DESCRIPTOR_FLAGS EQU 18
DEF FULL_COLOR_DESCRIPTOR_RETRY_TOKEN EQU 19
DEF FULL_COLOR_DESCRIPTOR_CLASS_MASK EQU $0f
DEF FULL_COLOR_DESCRIPTOR_STATE_MASK EQU $f0
DEF FULL_COLOR_DESCRIPTOR_STATE_SHIFT EQU 4
DEF FULL_COLOR_DESCRIPTOR_FREE EQU $f0

DEF FULL_COLOR_RESOURCE_PALETTES EQU 1 << 0
DEF FULL_COLOR_RESOURCE_BG_MAP EQU 1 << 1
DEF FULL_COLOR_RESOURCE_ATTRIBUTES EQU 1 << 2
DEF FULL_COLOR_RESOURCE_SHADOW_OAM EQU 1 << 3
DEF FULL_COLOR_RESOURCE_HARDWARE_OAM EQU 1 << 4
DEF FULL_COLOR_RESOURCE_TILE_DATA EQU 1 << 5
DEF FULL_COLOR_RESOURCE_ALL EQU $3f

; Exact visible-unit contracts. Rectangle-like requests encode width in the
; low desired-state byte and height in the high byte. Animation replacement
; encodes its attribute-map destination in desired-state instead.
DEF FULL_COLOR_BG_PALETTE_DESTINATION EQU rBGPD
DEF FULL_COLOR_OBJ_PALETTE_DESTINATION EQU rOBPD
DEF FULL_COLOR_OAM_DESTINATION EQU $c300
DEF FULL_COLOR_PALETTE_EXTENT EQU 64
IF DEF(FULL_COLOR_PRODUCTION_LINKAGE) && !DEF(PHASE2_AUDIT)
DEF FULL_COLOR_PALETTE_RESERVATION EQU FULL_COLOR_PRODUCTION_PALETTE_RESERVATION
ELSE
DEF FULL_COLOR_PALETTE_RESERVATION EQU 64
ENDC
DEF FULL_COLOR_OAM_EXTENT EQU OAM_COUNT * 4
IF DEF(FULL_COLOR_PRODUCTION_LINKAGE) && !DEF(PHASE2_AUDIT)
DEF FULL_COLOR_OAM_RESERVATION EQU FULL_COLOR_PRODUCTION_OAM_RESERVATION
ELSE
DEF FULL_COLOR_OAM_RESERVATION EQU OAM_COUNT * 5
ENDC
DEF FULL_COLOR_ANIMATION_TILE_BYTES EQU 16
DEF FULL_COLOR_ANIMATION_EXTENT EQU FULL_COLOR_ANIMATION_TILE_BYTES + 1
IF DEF(FULL_COLOR_PRODUCTION_LINKAGE) && !DEF(PHASE2_AUDIT)
DEF FULL_COLOR_ANIMATION_RESERVATION EQU FULL_COLOR_PRODUCTION_ANIMATION_RESERVATION
ELSE
DEF FULL_COLOR_ANIMATION_RESERVATION EQU FULL_COLOR_ANIMATION_EXTENT
ENDC
DEF FULL_COLOR_BG_MAP_FIRST EQU $9800
DEF FULL_COLOR_BG_MAP_LAST EQU $9fff
DEF FULL_COLOR_TILE_DATA_FIRST EQU $8000
DEF FULL_COLOR_TILE_DATA_LAST_START EQU $97f0

DEF FULL_COLOR_FLAG_OVERLAY EQU 1 << 0
DEF FULL_COLOR_FLAG_TRANSFORM EQU 1 << 1
IF DEF(PHASE2_AUDIT) || DEF(FULL_COLOR_PRODUCTION_LINKAGE)
DEF FULL_COLOR_FLAG_OAM_FINISHED EQU 1 << 2
DEF FULL_COLOR_FLAG_MOVEMENT_STRIP EQU 1 << 3
ENDC
DEF FULL_COLOR_ATTRIBUTE_FORBIDDEN_BIT EQU 1 << 4

DEF FULL_COLOR_FALLBACK_NONE EQU 0
DEF FULL_COLOR_FALLBACK_MISSING_IDENTITY EQU 1
DEF FULL_COLOR_FALLBACK_OUT_OF_RANGE EQU 2
DEF FULL_COLOR_FALLBACK_UNMAPPED EQU 3

DEF FULL_COLOR_TIMING_NONE EQU 0
DEF FULL_COLOR_TIMING_PALETTE_BG EQU 1
DEF FULL_COLOR_TIMING_PALETTE_OBJ EQU 2
DEF FULL_COLOR_TIMING_PAIRED_TRANSFER EQU 3
DEF FULL_COLOR_TIMING_OAM_MAXIMUM EQU 4

DEF FULL_COLOR_DEBUG_COMMAND_PHASE2_BASE EQU $20
DEF FULL_COLOR_DEBUG_CHECKPOINT_PHASE2_BASE EQU $20

; Guarded Phase 2 audit lifecycle/debug protocol. The carrier is internal ROM
; instrumentation, not a save format or public ABI.
DEF FULL_COLOR_AUTHORITY_SNAPSHOT_BYTES EQU 16
IF DEF(PHASE2_AUDIT)
DEF FULL_COLOR_DEBUG_COMMAND_CLEAR EQU FULL_COLOR_DEBUG_COMMAND_PHASE2_BASE + 0
DEF FULL_COLOR_DEBUG_COMMAND_ARM EQU FULL_COLOR_DEBUG_COMMAND_PHASE2_BASE + 1
DEF FULL_COLOR_DEBUG_COMMAND_SNAPSHOT EQU FULL_COLOR_DEBUG_COMMAND_PHASE2_BASE + 2
DEF FULL_COLOR_DEBUG_COMMAND_ACK EQU FULL_COLOR_DEBUG_COMMAND_PHASE2_BASE + 3
DEF FULL_COLOR_DEBUG_CHECKPOINT_CLEAR EQU FULL_COLOR_DEBUG_CHECKPOINT_PHASE2_BASE + 0
DEF FULL_COLOR_DEBUG_CHECKPOINT_ARMED EQU FULL_COLOR_DEBUG_CHECKPOINT_PHASE2_BASE + 1
DEF FULL_COLOR_DEBUG_CHECKPOINT_SNAPSHOT EQU FULL_COLOR_DEBUG_CHECKPOINT_PHASE2_BASE + 2
DEF FULL_COLOR_DEBUG_CHECKPOINT_ACKNOWLEDGED EQU FULL_COLOR_DEBUG_CHECKPOINT_PHASE2_BASE + 3
DEF FULL_COLOR_DEBUG_PROTOCOL_IDLE EQU 0
DEF FULL_COLOR_DEBUG_PROTOCOL_ARMED EQU 1
DEF FULL_COLOR_DEBUG_PROTOCOL_SNAPSHOTTED EQU 2
DEF FULL_COLOR_DEBUG_PROTOCOL_ACKNOWLEDGED EQU 3

DEF FULL_COLOR_DEBUG_CARRIER_BYTES EQU 295
DEF FULL_COLOR_DEBUG_TRACE_RECORD_BYTES EQU 24
DEF FULL_COLOR_DEBUG_TRACE_CAPACITY_PHASE2 EQU 8
ENDC

DEF FULL_COLOR_ASSERT_NONE EQU 0
DEF FULL_COLOR_ASSERT_GENERATION_EXHAUSTED EQU 1
DEF FULL_COLOR_ASSERT_OWNER_OR_GENERATION EQU 2
DEF FULL_COLOR_ASSERT_ILLEGAL_JOB_TRANSITION EQU 3
DEF FULL_COLOR_ASSERT_COMMIT_IN_PROGRESS EQU 4
DEF FULL_COLOR_ASSERT_DEBUG_COMMAND EQU 5

DEF FULL_COLOR_DEBUG_COMMAND_NONE EQU 0
DEF FULL_COLOR_DEBUG_COMMAND_OWNERSHIP_REPLACEMENT EQU 1
DEF FULL_COLOR_DEBUG_COMMAND_RESTORE_YELLOW EQU 2
DEF FULL_COLOR_DEBUG_CHECKPOINT_NONE EQU 0
DEF FULL_COLOR_DEBUG_CHECKPOINT_OWNERSHIP_REPLACEMENT EQU 1
DEF FULL_COLOR_DEBUG_CHECKPOINT_RESTORED_YELLOW EQU 2

DEF FULL_COLOR_DEBUG_WRITER_OWNERSHIP EQU 1
DEF FULL_COLOR_DEBUG_COMMIT_OWNERSHIP_REPLACEMENT EQU 1
DEF FULL_COLOR_DEBUG_RESOURCE_OWNERSHIP_GENERATION EQU 1
DEF FULL_COLOR_DEBUG_JOB_OLD EQU 1
DEF FULL_COLOR_DEBUG_JOB_REPLACEMENT EQU 2
DEF FULL_COLOR_DEBUG_REQUEST_OWNERSHIP_REPLACEMENT EQU 1

; Keep symbolic encodings in generated .sym files for runtime/model adapters.
EXPORT RENDERER_YELLOW, RENDERER_FULL_COLOR_OVERWORLD
EXPORT YELLOW_ACTIVE, HANDOFF_TO_OVERWORLD, OVERWORLD_RECONSTRUCTING
EXPORT OVERWORLD_ACTIVE, OVERWORLD_OVERLAY, HANDOFF_TO_YELLOW
IF DEF(FULL_COLOR_PRODUCTION_LINKAGE)
EXPORT YELLOW_RECONSTRUCTING
EXPORT RENDERER_CONTEXT_ORDINARY_MAP, RENDERER_CONTEXT_OVERLAY
EXPORT RENDERER_CONTEXT_DIALOGUE, RENDERER_CONTEXT_MENU
EXPORT RENDERER_CONTEXT_BATTLE, RENDERER_CONTEXT_STANDALONE
EXPORT RENDERER_CONTEXT_BOOT_RESET, NUM_RENDERER_CONTEXTS
EXPORT FULL_COLOR_PRODUCTION_ACTIVATED
EXPORT VBLANK_ROUTE_CLOSED, VBLANK_ROUTE_YELLOW, VBLANK_ROUTE_COLOR
EXPORT TRANSITION_NONE, TRANSITION_REQUIRED
EXPORT TRANSITION_ROUTE_NONE, TRANSITION_ROUTE_YELLOW
EXPORT TRANSITION_ROUTE_FULL_COLOR, TRANSITION_ROUTE_RESET_YELLOW
EXPORT FULL_COLOR_RECONSTRUCTION_ITEM_MAP_TILESET_OVERRIDES
EXPORT FULL_COLOR_RECONSTRUCTION_ITEM_VIEWPORT_DESTINATION
EXPORT FULL_COLOR_RECONSTRUCTION_ITEM_TILES_REPLACEMENTS
EXPORT FULL_COLOR_RECONSTRUCTION_ITEM_TILEMAPS_ATTRIBUTES
EXPORT FULL_COLOR_RECONSTRUCTION_ITEM_PALETTES
EXPORT FULL_COLOR_RECONSTRUCTION_ITEM_OAM
EXPORT FULL_COLOR_RECONSTRUCTION_ITEM_SCHEDULER
EXPORT FULL_COLOR_RECONSTRUCTION_ITEM_MACHINE_STATE
EXPORT FULL_COLOR_RECONSTRUCTION_LEDGER_COMPLETE
EXPORT BIT_COLOR_MODE_YELLOW, COLOR_MODE_COLOR, COLOR_MODE_YELLOW
ENDC
EXPORT ACCEPTED, COALESCED, DEFERRED, REJECTED_WRONG_OWNER
EXPORT REJECTED_STALE_GENERATION, REJECTED_CAPACITY
EXPORT PENDING, PREPARED, COMMITTING, COMPLETE, CANCELLED
EXPORT HANDOFF, RESET, SUPERSEDED, STALE_GENERATION
EXPORT RENDERER_JOB_NONE, CANCELLATION_NONE
EXPORT FULL_COLOR_DEBUG_COMMAND_NONE
EXPORT FULL_COLOR_DEBUG_COMMAND_OWNERSHIP_REPLACEMENT
EXPORT FULL_COLOR_DEBUG_COMMAND_RESTORE_YELLOW
EXPORT FULL_COLOR_DEBUG_CHECKPOINT_NONE
EXPORT FULL_COLOR_DEBUG_CHECKPOINT_OWNERSHIP_REPLACEMENT
EXPORT FULL_COLOR_DEBUG_CHECKPOINT_RESTORED_YELLOW
EXPORT FULL_COLOR_REQUEST_ANIMATION_REPLACEMENT
EXPORT FULL_COLOR_REQUEST_BG_PALETTE_PAYLOAD
EXPORT FULL_COLOR_REQUEST_MAP_COLUMN_PAIRED
EXPORT FULL_COLOR_REQUEST_MAP_CONNECTION_PAIRED
EXPORT FULL_COLOR_REQUEST_MAP_OVERLAY_PAIRED
EXPORT FULL_COLOR_REQUEST_MAP_RECTANGLE_PAIRED
EXPORT FULL_COLOR_REQUEST_MAP_ROW_PAIRED
EXPORT FULL_COLOR_REQUEST_OAM_BATCH_AND_DMA
EXPORT FULL_COLOR_REQUEST_OBJ_PALETTE_PAYLOAD
EXPORT NUM_FULL_COLOR_REQUEST_CLASSES
EXPORT FULL_COLOR_RESOURCE_PALETTES, FULL_COLOR_RESOURCE_BG_MAP
EXPORT FULL_COLOR_RESOURCE_ATTRIBUTES, FULL_COLOR_RESOURCE_SHADOW_OAM
EXPORT FULL_COLOR_RESOURCE_HARDWARE_OAM, FULL_COLOR_RESOURCE_TILE_DATA
EXPORT FULL_COLOR_RESOURCE_ALL
EXPORT FULL_COLOR_BG_PALETTE_DESTINATION, FULL_COLOR_OBJ_PALETTE_DESTINATION
EXPORT FULL_COLOR_OAM_DESTINATION, FULL_COLOR_PALETTE_EXTENT
EXPORT FULL_COLOR_PALETTE_RESERVATION, FULL_COLOR_OAM_EXTENT
EXPORT FULL_COLOR_OAM_RESERVATION, FULL_COLOR_ANIMATION_EXTENT
EXPORT FULL_COLOR_ANIMATION_RESERVATION
IF DEF(PHASE2_AUDIT) || DEF(FULL_COLOR_PRODUCTION_LINKAGE)
EXPORT FULL_COLOR_FLAG_OVERLAY, FULL_COLOR_FLAG_TRANSFORM
EXPORT FULL_COLOR_FLAG_OAM_FINISHED, FULL_COLOR_FLAG_MOVEMENT_STRIP
ENDC
EXPORT FULL_COLOR_FALLBACK_NONE, FULL_COLOR_FALLBACK_MISSING_IDENTITY
EXPORT FULL_COLOR_FALLBACK_OUT_OF_RANGE, FULL_COLOR_FALLBACK_UNMAPPED
IF DEF(PHASE2_AUDIT)
EXPORT FULL_COLOR_DEBUG_COMMAND_CLEAR, FULL_COLOR_DEBUG_COMMAND_ARM
EXPORT FULL_COLOR_DEBUG_COMMAND_SNAPSHOT, FULL_COLOR_DEBUG_COMMAND_ACK
EXPORT FULL_COLOR_DEBUG_CHECKPOINT_CLEAR, FULL_COLOR_DEBUG_CHECKPOINT_ARMED
EXPORT FULL_COLOR_DEBUG_CHECKPOINT_SNAPSHOT
EXPORT FULL_COLOR_DEBUG_CHECKPOINT_ACKNOWLEDGED
ENDC
