blank_issues_enabled: false
contact_links:
  - name: Project Discord
    url: https://discord.com/invite/
    about: If you need help with pokeyellow, or have general questions about the project, ask in the project Discord server.
