"""Stable symbolic vocabulary from the normative requirements.

The string spellings are contractual. Numeric values deliberately do not
exist here; ROM encodings are supplied separately to the trace decoder.
"""

from enum import StrEnum


class Owner(StrEnum):
    RENDERER_YELLOW = "RENDERER_YELLOW"
    RENDERER_FULL_COLOR_OVERWORLD = "RENDERER_FULL_COLOR_OVERWORLD"


class Phase(StrEnum):
    YELLOW_ACTIVE = "YELLOW_ACTIVE"
    HANDOFF_TO_OVERWORLD = "HANDOFF_TO_OVERWORLD"
    OVERWORLD_RECONSTRUCTING = "OVERWORLD_RECONSTRUCTING"
    OVERWORLD_ACTIVE = "OVERWORLD_ACTIVE"
    OVERWORLD_OVERLAY = "OVERWORLD_OVERLAY"
    HANDOFF_TO_YELLOW = "HANDOFF_TO_YELLOW"
    YELLOW_RECONSTRUCTING = "YELLOW_RECONSTRUCTING"


class RequestResult(StrEnum):
    ACCEPTED = "ACCEPTED"
    COALESCED = "COALESCED"
    DEFERRED = "DEFERRED"
    REJECTED_WRONG_OWNER = "REJECTED_WRONG_OWNER"
    REJECTED_STALE_GENERATION = "REJECTED_STALE_GENERATION"
    REJECTED_CAPACITY = "REJECTED_CAPACITY"


class JobState(StrEnum):
    PENDING = "PENDING"
    PREPARED = "PREPARED"
    COMMITTING = "COMMITTING"
    COMPLETE = "COMPLETE"
    CANCELLED = "CANCELLED"


class CancellationReason(StrEnum):
    HANDOFF = "HANDOFF"
    RESET = "RESET"
    SUPERSEDED = "SUPERSEDED"
    STALE_GENERATION = "STALE_GENERATION"


class OverlayCell(StrEnum):
    OPAQUE_OVERLAY = "OPAQUE_OVERLAY"
    REVEALED_TERRAIN = "REVEALED_TERRAIN"


class OverlayDestination(StrEnum):
    BG_MAP_9800 = "BG_MAP_9800"
    BG_MAP_9C00 = "BG_MAP_9C00"
    WINDOW_MAP_9800 = "WINDOW_MAP_9800"
    WINDOW_MAP_9C00 = "WINDOW_MAP_9C00"


class ReconstructionProvenance(StrEnum):
    REQUEST_AUTHORITATIVE_STATE = "REQUEST_AUTHORITATIVE_STATE"
    FRESHLY_GENERATED_STATE = "FRESHLY_GENERATED_STATE"
    INITIALIZED_SCHEDULER_STATE = "INITIALIZED_SCHEDULER_STATE"
    RESTORED_MACHINE_STATE = "RESTORED_MACHINE_STATE"
    CAPTURED_VRAM = "CAPTURED_VRAM"
    SAVED_VRAM = "SAVED_VRAM"
    CAPTURED_PALETTE_RAM = "CAPTURED_PALETTE_RAM"
    SAVED_PALETTE_RAM = "SAVED_PALETTE_RAM"
    CAPTURED_OAM = "CAPTURED_OAM"
    SAVED_OAM = "SAVED_OAM"
    CAPTURED_SCREEN_BUFFER = "CAPTURED_SCREEN_BUFFER"
    SAVED_SCREEN_BUFFER = "SAVED_SCREEN_BUFFER"


class OAMFallbackKind(StrEnum):
    MISSING_IDENTITY = "MISSING_IDENTITY"
    OUT_OF_RANGE_IDENTITY = "OUT_OF_RANGE_IDENTITY"
    UNMAPPED_IDENTITY = "UNMAPPED_IDENTITY"
