name: Release

on:
  workflow_run:
    workflows: [CI]
    types: [completed]

permissions:
  actions: read
  contents: write

jobs:
  release:
    name: Release
    if: >-
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'push'
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v8
        with:
          name: pokeyellow-build
          path: release
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Create GitHub release
        uses: softprops/action-gh-release@v3
        with:
          files: release/*
          name: Pokeyellow (${{ github.run_number }})
          tag_name: build-${{ github.run_number }}
          generate_release_notes: true
